[package]
name = "waves"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
color-eyre = "0.6.5"
serde_json = "1.0.145"

acoustid_api = { path = "acoustid_api" }
metadata = { path = "metadata" }
